from __future__ import annotations

import argparse
from pathlib import Path

from generate_full_dataset import generate_full_dataset


def _parse_sizes(raw: str) -> list[int]:
    values: list[int] = []
    for chunk in raw.split(","):
        cleaned = chunk.strip()
        if cleaned:
            values.append(int(cleaned))
    return values


def _split_counts(total: int, basic_ratio: float) -> tuple[int, int]:
    n_basic = int(total * basic_ratio)
    n_llm = total - n_basic
    return n_basic, n_llm


def _folder_name(total: int, n_basic: int, n_llm: int) -> str:
    return f"{total}({n_basic}-{n_llm})"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate multiple full_outputs dataset folders by size.")
    parser.add_argument(
        "--sizes",
        type=str,
        default="2000,4000,6000,8000,10000",
        help="Comma-separated total dataset sizes.",
    )
    parser.add_argument(
        "--basic-ratio",
        type=float,
        default=0.5,
        help="Share of examples generated by basic template generator.",
    )
    parser.add_argument(
        "--base-output",
        type=str,
        default="LNIAGIA/query_parsing_models/data_generation/full_outputs",
        help="Parent directory for generated folders.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Seed passed into generate_full_dataset.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Regenerate folders even when train/val/test files already exist.",
    )
    args = parser.parse_args()

    base_output = Path(args.base_output)
    sizes = _parse_sizes(args.sizes)

    if not sizes:
        raise ValueError("No sizes were provided.")

    print("=" * 72)
    print("Generating size sweep")
    print("=" * 72)
    print(f"Base output : {base_output}")
    print(f"Sizes       : {sizes}")
    print(f"Basic ratio : {args.basic_ratio}")
    print("=" * 72)

    for total in sizes:
        n_basic, n_llm = _split_counts(total, args.basic_ratio)
        folder = base_output / _folder_name(total, n_basic, n_llm)

        expected_files = [folder / "train.json", folder / "val.json", folder / "test.json", folder / "stats.json"]
        if not args.overwrite and all(path.exists() for path in expected_files):
            print(f"[SKIP] {folder} already exists.")
            continue

        print(f"\n[RUN ] total={total} | basic={n_basic} | llm={n_llm} -> {folder}")

        generate_full_dataset(
            output_dir=str(folder),
            n_basic_generator=n_basic,
            n_llm_generator=n_llm,
            validate_all_llm_data=True,
            llm_validation_sample_rate=1.0,
            training_target="bio",
            bio_training_source="hybrid_projected",
            canonical_export_mode=True,
            seed=args.seed,
        )

    print("\nSize sweep generation complete.")


if __name__ == "__main__":
    main()
